version: 2

common: &common
  directories:
    - "**/*"
  schedule:
    interval: "cron"
    cronjob: "0 0 1 * *"

updates:
  - package-ecosystem: "github-actions"
    groups:
      github-actions:
        patterns:
          - '*'
    <<: *common
  - package-ecosystem: "npm"
    groups:
      npm:
        patterns:
          - '*'
    <<: *common